/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Cuenta;
import java.util.ArrayList;
/**
 *
 * @author pared
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Cuenta aux, persona;
    ArrayList <Cuenta> v = new ArrayList();
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroIdentificacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSaldoAIngresar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSaldoRetirar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReciboCuenta = new javax.swing.JTextArea();
        cmbIngresar = new javax.swing.JButton();
        cmbGuardar = new javax.swing.JButton();
        cmbSalir = new javax.swing.JButton();
        cmbRetirar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("BANCO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Numero de Identificacion:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));
        jPanel1.add(txtNumeroIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 110, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Saldo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 60, -1));

        txtSaldo.setEditable(false);
        jPanel1.add(txtSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 110, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Saldo a Ingresar:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));
        jPanel1.add(txtSaldoAIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 110, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Cantidad a Retirar:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));
        jPanel1.add(txtSaldoRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 110, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Recibo Cuenta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtReciboCuenta.setEditable(false);
        txtReciboCuenta.setColumns(20);
        txtReciboCuenta.setRows(5);
        jScrollPane1.setViewportView(txtReciboCuenta);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 290, 130));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 320, 160));

        cmbIngresar.setText("Ingresar");
        cmbIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(cmbIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 90, -1));

        cmbGuardar.setText("Guardar");
        cmbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(cmbGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 90, -1));

        cmbSalir.setText("Salir");
        jPanel1.add(cmbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 90, -1));

        cmbRetirar.setText("Retirar");
        cmbRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRetirarActionPerformed(evt);
            }
        });
        jPanel1.add(cmbRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIngresarActionPerformed
        // TODO add your handling code here:
        String aux3;
        long numidentf;
        double montingre, montsacar=0, saldoactual=0;
        
        numidentf= Long.parseLong(txtNumeroIdentificacion.getText());
        montingre= Double.parseDouble(txtSaldoAIngresar.getText());
        
        persona= new Cuenta (numidentf, saldoactual,montsacar, montingre);
        aux= persona.Ingresar(persona);
        v.add(aux);
        txtSaldo.setText(""+aux.getSaldo_actual());
        for (int i = 0; i < v.size(); i++) 
        {aux3= "Identificacion: " + v.get(i).getNumero_cuenta()+ "\n"
                  + "Saldo Actual: " + v.get(i).getSaldo_actual() + "\n"
                  + "Saldo Ingresado: " + v.get(i).getIngresar_saldo() + "\n"
                  + "Saldo Retirado: " + v.get(i).getRetirar_saldo() + "\n\n";
          
            txtReciboCuenta.append(aux3);
        }
        
    }//GEN-LAST:event_cmbIngresarActionPerformed

    private void cmbRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRetirarActionPerformed
        // TODO add your handling code here:
        String aux2;
        long numidentf;
        double saldoactual, montsacar, montingre;
        aux= persona.retirar(persona);
        v.add(aux);
        for (int i = 0; i < v.size(); i++) 
        {
            
            aux2= "Identificacion: " + v.get(i).getNumero_cuenta()+ "\n"
                  + "Saldo Actual: " + v.get(i).getSaldo_actual() + "\n"
                  + "Saldo Ingresado: " + v.get(i).getIngresar_saldo() + "\n"
                  + "Saldo Retirado: " + v.get(i).getRetirar_saldo() + "\n\n";
          
            txtReciboCuenta.append(aux2);
            
        }
        
        
    }//GEN-LAST:event_cmbRetirarActionPerformed

    private void cmbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGuardarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbGuardar;
    private javax.swing.JButton cmbIngresar;
    private javax.swing.JButton cmbRetirar;
    private javax.swing.JButton cmbSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtNumeroIdentificacion;
    private javax.swing.JTextArea txtReciboCuenta;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtSaldoAIngresar;
    private javax.swing.JTextField txtSaldoRetirar;
    // End of variables declaration//GEN-END:variables

    private static class Arraylist<T> {

        private int size;

        public Arraylist() {
        }

        private void add(Cuenta aux) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}
