/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Cuenta;
import javax.swing.JOptionPane;
/**
 *
 * @author pared
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Cuenta persona;
    
    public Principal() {
        initComponents();
        cmbCrearCuenta.setEnabled(true);
        cmbGuardar.setEnabled(false);
        cmbIngresar.setEnabled(false);
        cmbRetirar.setEnabled(false);
        cmbSalir.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroIdentificacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSaldoAIngresar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSaldoRetirar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReciboCuenta = new javax.swing.JTextArea();
        cmbIngresar = new javax.swing.JButton();
        cmbGuardar = new javax.swing.JButton();
        cmbSalir = new javax.swing.JButton();
        cmbRetirar = new javax.swing.JButton();
        cmbCrearCuenta = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtNoCuenta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("BANCO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Numero de Identificacion:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtNumeroIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroIdentificacionKeyTyped(evt);
            }
        });
        jPanel1.add(txtNumeroIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 110, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Saldo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 60, -1));

        txtSaldo.setEditable(false);
        jPanel1.add(txtSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 110, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Saldo a Ingresar:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        txtSaldoAIngresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldoAIngresarKeyTyped(evt);
            }
        });
        jPanel1.add(txtSaldoAIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 110, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Cantidad a Retirar:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        txtSaldoRetirar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldoRetirarKeyTyped(evt);
            }
        });
        jPanel1.add(txtSaldoRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 110, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Recibo Cuenta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtReciboCuenta.setEditable(false);
        txtReciboCuenta.setColumns(20);
        txtReciboCuenta.setRows(5);
        jScrollPane1.setViewportView(txtReciboCuenta);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 290, 130));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 320, 160));

        cmbIngresar.setText("Ingresar");
        cmbIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbIngresarActionPerformed(evt);
            }
        });
        cmbIngresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbIngresarKeyPressed(evt);
            }
        });
        jPanel1.add(cmbIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 120, -1));

        cmbGuardar.setText("Mostrar");
        cmbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(cmbGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 120, -1));

        cmbSalir.setText("Salir");
        cmbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSalirActionPerformed(evt);
            }
        });
        jPanel1.add(cmbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 120, -1));

        cmbRetirar.setText("Retirar");
        cmbRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRetirarActionPerformed(evt);
            }
        });
        jPanel1.add(cmbRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 120, -1));

        cmbCrearCuenta.setText("Crear Cuenta");
        cmbCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCrearCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(cmbCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 120, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Numero de Cuenta:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        txtNoCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNoCuentaKeyTyped(evt);
            }
        });
        jPanel1.add(txtNoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIngresarActionPerformed
        // TODO add your handling code here:
        double montingresar;
        
        montingresar= Double.parseDouble(txtSaldoAIngresar.getText());
        persona.ingresar(montingresar);
        txtSaldo.setText(""+persona.getSaldo_actual());
        
        txtSaldoAIngresar.setText("");
        cmbCrearCuenta.setEnabled(false);
        cmbGuardar.setEnabled(true);
        cmbIngresar.setEnabled(true);
        cmbRetirar.setEnabled(true);
        cmbSalir.setEnabled(true);
    }//GEN-LAST:event_cmbIngresarActionPerformed

    private void cmbRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRetirarActionPerformed
        // TODO add your handling code here:
        double montretirar;
        montretirar = Double.parseDouble(txtSaldoRetirar.getText());
        
        if (montretirar> persona.getSaldo_actual())
        {
            JOptionPane.showMessageDialog(this, "Saldo Insuficiente", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else 
        {
           persona.retirar(montretirar);
           txtSaldo.setText(""+persona.getSaldo_actual());
        }
        
        txtSaldoRetirar.setText("");
        cmbCrearCuenta.setEnabled(false);
        cmbGuardar.setEnabled(true);
        cmbIngresar.setEnabled(true);
        cmbRetirar.setEnabled(true);
        cmbSalir.setEnabled(true);
    }//GEN-LAST:event_cmbRetirarActionPerformed

    private void cmbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGuardarActionPerformed
        // TODO add your handling code here:
        String mostrar; 
        mostrar= persona.mostrar();
        txtReciboCuenta.append(mostrar);
        cmbCrearCuenta.setEnabled(true);
        cmbGuardar.setEnabled(false);
        cmbIngresar.setEnabled(false);
        cmbRetirar.setEnabled(false);
        cmbSalir.setEnabled(true);
    }//GEN-LAST:event_cmbGuardarActionPerformed

    private void cmbIngresarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbIngresarKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbIngresarKeyPressed

    private void cmbCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCrearCuentaActionPerformed
        // TODO add your handling code here:
        long noidenti, nocuenta;
        
        noidenti = Long.parseLong(txtNumeroIdentificacion.getText());
        nocuenta = Long.parseLong(txtNoCuenta.getText());
        
        persona = new Cuenta (nocuenta, noidenti);
        
        JOptionPane.showMessageDialog(this, "Cuenta Creada Correctamente");
        cmbCrearCuenta.setEnabled(false);
        cmbGuardar.setEnabled(true);
        cmbIngresar.setEnabled(true);
        cmbRetirar.setEnabled(true);
        cmbSalir.setEnabled(true);
    }//GEN-LAST:event_cmbCrearCuentaActionPerformed

    private void cmbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSalirActionPerformed
        // TODO add your handling code here:
        txtNoCuenta.setText("");
        txtNumeroIdentificacion.setText("");
        txtReciboCuenta.setText("");
        txtSaldo.setText("");
        txtSaldoAIngresar.setText("");
        txtSaldoRetirar.setText("");
        cmbCrearCuenta.setEnabled(true);
        cmbGuardar.setEnabled(false);
        cmbIngresar.setEnabled(false);
        cmbRetirar.setEnabled(false);
        cmbSalir.setEnabled(false);
    }//GEN-LAST:event_cmbSalirActionPerformed

    private void txtNoCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoCuentaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNoCuentaKeyTyped

    private void txtNumeroIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroIdentificacionKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNumeroIdentificacionKeyTyped

    private void txtSaldoAIngresarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoAIngresarKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtSaldoAIngresarKeyTyped

    private void txtSaldoRetirarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoRetirarKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtSaldoRetirarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbCrearCuenta;
    private javax.swing.JButton cmbGuardar;
    private javax.swing.JButton cmbIngresar;
    private javax.swing.JButton cmbRetirar;
    private javax.swing.JButton cmbSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtNoCuenta;
    private javax.swing.JTextField txtNumeroIdentificacion;
    private javax.swing.JTextArea txtReciboCuenta;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtSaldoAIngresar;
    private javax.swing.JTextField txtSaldoRetirar;
    // End of variables declaration//GEN-END:variables

    private static class Arraylist<T> {

        private int size;

        public Arraylist() {
        }

        private void add(Cuenta aux) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}
